### ISSUE TITLE
Bug when set Localization

### ISSUE THREAD

**Issue by vertexgren** [cyon/vue-translation-manager#49]
![Снимок экрана 2023-06-30 в 15 51 33](https://github.com/cyon/vue-translation-manager/assets/107301050/4e91cffe-d56f-4398-8f69-ca610a67d091)

When i set translation, i have too many null values in my locales/en.json

**Comment by vertexgren** [comment]
fixed with adding --add-key to 
vue-translation-manager translate --add-key <---- like this

**Comment by nuykon** [comment]
I have the same behavior, the same error, if I run the vue-translation-manager translate command.

"fixed with adding --add-key" - this parameter does not help

Perhaps you meant - --ask-key - but this is not the solution to the problem.

I don't want to invent and enter the names of keys (and or paths to them).

**Comment by nuykon** [comment]
fixed in my fork - https://www.npmjs.com/package/@nuykon/vue-translation-manager
